apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: demo-service
  namespace: demo-service
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: demo-service
      sectionName: https
  validation:
    hostname: demo-service.demo-service.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: tc-jku-internal-ca
