apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: demo-service
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: demo-service
      sectionName: https
  validation:
    hostname: {{ include "demo-service.backendHostname" . }}
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: {{ .Values.trustBundleName }}

