apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-service-backend
  namespace: {{ .Release.Namespace }}
spec:
  secretName: demo-service-backend-tls
  # Deliberately short duration for testing with demo service
  duration: {{ .Values.certificate.duration | quote }}
  # Renew 15 minutes before expiry
  renewBefore: {{ .Values.certificate.renewBefore | quote }}

  issuerRef:
    group: cert-manager.io
    kind: {{ .Values.certificate.issuerRef.kind }}
    name: {{ .Values.certificate.issuerRef.name }}

  dnsNames:
    - {{ include "demo-service.backendHostname" . }}

  privateKey:
    algorithm: ECDSA
    size: 256
    encoding: PKCS8
    # Always also create new private key for demo purposes
    rotationPolicy: Always

  usages:
    - digital signature
    - server auth

