apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: authentik
  namespace: authentik
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: authentik-server
      sectionName: https
  validation:
    hostname: authentik-server.authentik.svc.cluster.local
    caCertificateRefs:
      - group: ""
        kind: ConfigMap
        name: tc-jku-internal-ca
