apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data
  namespace: authentik
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-app
  namespace: authentik
automountServiceAccountToken: false
