nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /var/mnt/local-storage

storageClass:
  create: true
  defaultClass: true
  defaultVolumeType: hostPath
  name: local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsUser: 65534
  runAsGroup: 65534

helperImage:
  tag: "1.37.0"
